export const BetSlipsTypes = {
  TOGGLE_BET_SLIP: 'TOGGLE_BET_SLIP',
  REMOVE_BET_SLIP: 'REMOVE_BET_SLIP',
  REMOVE_ALL_BET_SLIPS: 'REMOVE_ALL_BET_SLIPS',
  ADD_VALUES_TO_BET_SLIP: 'ADD_VALUES_TO_BET_SLIP',
};
