export const PlayerRankingsTypes = {
  FETCH_PLAYER_RANKIGNS_REQUEST: 'FETCH_PLAYER_RANKIGNS_REQUEST',
  FETCH_PLAYER_RANKIGNS_SUCCESS: 'FETCH_PLAYER_RANKIGNS_SUCCESS',
  FETCH_PLAYER_RANKIGNS_FAILURE: 'FETCH_PLAYER_RANKIGNS_FAILURE',
};
